[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]

solc_version = "0.8.27"

[dependencies]
forge-std = "1.9.4"
eth-infinitism-account-abstraction = "0.7"
erc6551-reference = "0.3.1"
safe-global-safe-smart-account = "1.4.1-3"
"@openzeppelin-contracts" = "5.1.0"
"@openzeppelin-contracts-upgradeable" = "5.1.0"
